// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route_guide.proto

package routeguide

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Point struct {
	Latitude             int32    `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            int32    `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Rectangle struct {
	Lo                   *Point   `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	Hi                   *Point   `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{1}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetLo() *Point {
	if m != nil {
		return m.Lo
	}
	return nil
}

func (m *Rectangle) GetHi() *Point {
	if m != nil {
		return m.Hi
	}
	return nil
}

type Feature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             *Point   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{2}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

type Image struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{3}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ImageSize struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageSize) Reset()         { *m = ImageSize{} }
func (m *ImageSize) String() string { return proto.CompactTextString(m) }
func (*ImageSize) ProtoMessage()    {}
func (*ImageSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7d679f20da65b7b, []int{4}
}

func (m *ImageSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageSize.Unmarshal(m, b)
}
func (m *ImageSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageSize.Marshal(b, m, deterministic)
}
func (m *ImageSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageSize.Merge(m, src)
}
func (m *ImageSize) XXX_Size() int {
	return xxx_messageInfo_ImageSize.Size(m)
}
func (m *ImageSize) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageSize.DiscardUnknown(m)
}

var xxx_messageInfo_ImageSize proto.InternalMessageInfo

func (m *ImageSize) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "routeguide.Point")
	proto.RegisterType((*Rectangle)(nil), "routeguide.Rectangle")
	proto.RegisterType((*Feature)(nil), "routeguide.Feature")
	proto.RegisterType((*Image)(nil), "routeguide.Image")
	proto.RegisterType((*ImageSize)(nil), "routeguide.ImageSize")
}

func init() { proto.RegisterFile("route_guide.proto", fileDescriptor_b7d679f20da65b7b) }

var fileDescriptor_b7d679f20da65b7b = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0x60, 0xb4, 0x19, 0x7b, 0xe9, 0x94, 0x82, 0x44, 0x41, 0xdd, 0x53, 0x2f, 0x06,
	0xa9, 0xe0, 0x51, 0x10, 0xc1, 0x22, 0xe4, 0xa0, 0xeb, 0x03, 0xc8, 0x9a, 0x2c, 0xe9, 0xc2, 0x36,
	0x2b, 0xc9, 0xe4, 0xd2, 0x37, 0xf4, 0xad, 0x24, 0x93, 0x26, 0xad, 0xb4, 0xbd, 0xcd, 0x7e, 0xf3,
	0xcd, 0x6f, 0xfe, 0xb0, 0x30, 0x2e, 0x5d, 0x4d, 0xfa, 0x2b, 0xaf, 0x4d, 0xa6, 0xe3, 0x9f, 0xd2,
	0x91, 0x43, 0x60, 0x89, 0x15, 0xf1, 0x0c, 0xc1, 0xbb, 0x33, 0x05, 0x61, 0x04, 0x43, 0xab, 0xc8,
	0x50, 0x9d, 0xe9, 0x0b, 0xef, 0xc6, 0x9b, 0x05, 0xb2, 0x7f, 0xe3, 0x15, 0x84, 0xd6, 0x15, 0x79,
	0x9b, 0xf4, 0x39, 0xb9, 0x15, 0xc4, 0x07, 0x84, 0x52, 0xa7, 0xa4, 0x8a, 0xdc, 0x6a, 0xbc, 0x05,
	0xdf, 0x3a, 0x06, 0x9c, 0xcf, 0xc7, 0xf1, 0xb6, 0x51, 0xcc, 0x5d, 0xa4, 0x6f, 0x5d, 0x63, 0x59,
	0x1a, 0xc6, 0x1c, 0xb6, 0x2c, 0x8d, 0x48, 0xe0, 0xec, 0x55, 0x2b, 0xaa, 0x4b, 0x8d, 0x08, 0x27,
	0x85, 0x5a, 0xb5, 0x33, 0x85, 0x92, 0x63, 0xbc, 0x83, 0xa1, 0x75, 0xa9, 0x22, 0xe3, 0x8a, 0xe3,
	0x9c, 0xde, 0x22, 0x2e, 0x21, 0x78, 0x5b, 0xa9, 0x9c, 0x59, 0x99, 0x22, 0xc5, 0xac, 0x91, 0xe4,
	0x58, 0x5c, 0x43, 0xc8, 0xc9, 0x4f, 0xb3, 0x66, 0x43, 0x65, 0xd6, 0xdd, 0x01, 0x38, 0x9e, 0xff,
	0x7a, 0x00, 0xb2, 0x81, 0x2f, 0x1a, 0x38, 0x3e, 0x02, 0x2c, 0x34, 0x75, 0xd3, 0xed, 0xf7, 0x8d,
	0x26, 0xbb, 0xd2, 0xc6, 0x27, 0x06, 0xf8, 0x04, 0xa3, 0xc4, 0x54, 0x5d, 0x61, 0x85, 0xd3, 0x5d,
	0x5b, 0x7f, 0xbf, 0x23, 0xd5, 0xf7, 0x1e, 0xbe, 0xc0, 0x44, 0xea, 0xd4, 0x95, 0x59, 0xb2, 0x59,
	0xab, 0x5d, 0xe9, 0xdf, 0x00, 0x2c, 0x45, 0xd3, 0x3d, 0xa9, 0xd9, 0x4d, 0x0c, 0x66, 0xde, 0xf7,
	0x29, 0x7f, 0x80, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0xe6, 0x6d, 0x23, 0x15, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteGuideClient is the client API for RouteGuide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteGuideClient interface {
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_ListFeaturesClient, error)
	RecordLocationImage(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RecordLocationImageClient, error)
}

type routeGuideClient struct {
	cc *grpc.ClientConn
}

func NewRouteGuideClient(cc *grpc.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/routeguide.RouteGuide/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_ListFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[0], "/routeguide.RouteGuide/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RouteGuide_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type routeGuideListFeaturesClient struct {
	grpc.ClientStream
}

func (x *routeGuideListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) RecordLocationImage(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RecordLocationImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RouteGuide_serviceDesc.Streams[1], "/routeguide.RouteGuide/RecordLocationImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideRecordLocationImageClient{stream}
	return x, nil
}

type RouteGuide_RecordLocationImageClient interface {
	Send(*Image) error
	CloseAndRecv() (*ImageSize, error)
	grpc.ClientStream
}

type routeGuideRecordLocationImageClient struct {
	grpc.ClientStream
}

func (x *routeGuideRecordLocationImageClient) Send(m *Image) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideRecordLocationImageClient) CloseAndRecv() (*ImageSize, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImageSize)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RouteGuideServer is the server API for RouteGuide service.
type RouteGuideServer interface {
	GetFeature(context.Context, *Point) (*Feature, error)
	ListFeatures(*Rectangle, RouteGuide_ListFeaturesServer) error
	RecordLocationImage(RouteGuide_RecordLocationImageServer) error
}

// UnimplementedRouteGuideServer can be embedded to have forward compatible implementations.
type UnimplementedRouteGuideServer struct {
}

func (*UnimplementedRouteGuideServer) GetFeature(ctx context.Context, req *Point) (*Feature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (*UnimplementedRouteGuideServer) ListFeatures(req *Rectangle, srv RouteGuide_ListFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFeatures not implemented")
}
func (*UnimplementedRouteGuideServer) RecordLocationImage(srv RouteGuide_RecordLocationImageServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordLocationImage not implemented")
}

func RegisterRouteGuideServer(s *grpc.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routeguide.RouteGuide/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteGuideServer).ListFeatures(m, &routeGuideListFeaturesServer{stream})
}

type RouteGuide_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type routeGuideListFeaturesServer struct {
	grpc.ServerStream
}

func (x *routeGuideListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _RouteGuide_RecordLocationImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteGuideServer).RecordLocationImage(&routeGuideRecordLocationImageServer{stream})
}

type RouteGuide_RecordLocationImageServer interface {
	SendAndClose(*ImageSize) error
	Recv() (*Image, error)
	grpc.ServerStream
}

type routeGuideRecordLocationImageServer struct {
	grpc.ServerStream
}

func (x *routeGuideRecordLocationImageServer) SendAndClose(m *ImageSize) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideRecordLocationImageServer) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RouteGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routeguide.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _RouteGuide_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _RouteGuide_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordLocationImage",
			Handler:       _RouteGuide_RecordLocationImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "route_guide.proto",
}
